### ISSUE TITLE
[Membership Plans and Pricing] Upgrade membership

### ISSUE THREAD

**Issue by TNTN95** [TNTN95/TNTN95.github.io#36]
**As a** member
**I want** an easy way to upgrade my membership or access special offers on the website
**so that** I can improve my experience and enjoy added benefits.

**AC:**
•	Easy process for members to upgrade their membership or access special offers.

**Comment by Trymnyheim** [comment]
Nice to have, but not prioritized.

**Comment by Torslu** [comment]
Won't be prioritized at the current moment.
